---
{{ if eq .Values.jwt.create true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwt.secretName }}
data:
  {{- $files := .Files }}
  {{- range tuple "jwt-public.pem" }}
  {{ . }}: |-
    {{ $files.Get . | b64enc }}
  {{- end }}
{{ end }}