apiVersion: apps/v1
kind: Deployment
metadata:
  name: therm-app
  labels:
    app: therm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: therm-app
  template:
    metadata:
      labels:
        app: therm-app
    spec:
      containers:
        - name: therm-app
          image: ghcr.io/pokebadgerswithspoon/rpi-therm/thermometer-app:{{ .Values.image.tag }}
          env:
            - name: QUARKUS_HTTP_HTTP2
              value: "false"
            - name: QUARKUS_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http