---
- name: DS18B20 support
  hosts: all
  become: true
  vars:
    dir: /opt/therm
    comment: "Raimondi juures"
  tasks:
  - name: Kernel module 
    community.general.modprobe:
      name: {{ item }}
      state: present
      persistent: present 
    loop:
      - w1-gpio
      - w1-therm
  - name: Creates directory
    ansible.builtin.file:
      path: {{ dir }}/{{ item }}
      state: directory
    loop:
      - bin
      - conf
  - name: Install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - openssl
      - base64
      - curl
  - name: Generate JWT private key
    community.crypto.openssl_privatekey:
      path: "{{ dir }}/conf/jwt.pem"
  - name: Generate JWT public key
    community.crypto.openssl_publickey:
      path: "{{ dir }}/conf/jwt.pem.pub"
      privatekey_path: "{{ dir }}/conf/jwt.pem"
  - name: Add script
    ansible.builtin.copy:
      src: "bin/thermometer_{{ item }}.sh"
      dest: "{{ dir }}/bin/"
      mode: "0755"
      force: true
    loop:
      - thermometer_json.sh
      - thermometer_post.sh
      - thermometer_jwt.sh
  - name: Crontab job
    ansible.builtin.cron:
      name: "Post temperature json"
      minute: "*/1"
      job: "{{ dir }}/bin/post > /dev/null"