---
- name: Thermometer local http server
  hosts: all
  become: true
  vars:
    dir: /opt/therm
  tasks:
  - name: Install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - nginx
      - fcgiwrap
  - name: Configure fcgiwrap.conf
    ansible.builtin.copy:
      src: "fcgiwrap.conf"
      dest: "/etc/nginx/fcgiwrap.conf"
      mode: "0644"
  - name: Creates directory
    ansible.builtin.file:
      path: "/var/www/cgi-bin"
      state: directory
  - name: Add cgi script
    ansible.builtin.copy:
      src: "cgi-bin/index.cgi"
      dest: "/var/www/cgi-bin/index.cgi"
      mode: "0755"
  - name: Add html
    ansible.builtin.copy:
      src: "index.html"
      dest: "/var/www/index.html"
      mode: "0755"