name: Run tests
on:  
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Test with Maven
        run:  ./thermometer-app/mvnw -f ./thermometer-app/pom.xml -B clean test
